### ISSUE TITLE
Setup Travis CI for continuos builds after each commit and upload resulted AppImage

### ISSUE THREAD

**Issue by Symbian9** [jonno85uk/chestnut#111] opened 2020-02-07 23:51 UTC
### TODO

0. [ ] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any AppImage packaging questions & support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by jonno85uk** [comment] 2020-02-08 12:30
Thanks for the info. I need to finally sort out the appimage.

**Comment by jonno85uk** [comment] 2020-02-09 19:58
An appimage will not be created for each commit because I have seen the hassle that causes. e.g users use a development build and create bugs which don't need to exist (I have been lurking on the Olive Issue tracker until I got locked).

Instead appimages will only be made available for released versions.

**Comment by jonno85uk** [comment] 2020-02-09 21:16
linuxdeploy-qt requires an ancient Ubuntu version (14.04). Chestnut will not build on anything later than 19.10. https://github.com/probonopd/linuxdeployqt/issues/340

**Comment by jonno85uk** [comment] 2020-02-09 21:20
As I will not entertain the idea of a CI build appimage this issue is a dupe of #48

**Closed by jonno85uk** 2020-02-09 21:20 UTC
Labels: build
